language: python
python:
  - "2.7"
#command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install codecov

# command to run tests
script:
    - cd tests
    - pytest --cov=./
after_success:
  - codecov


